services:
  llama:
    image: ollama/ollama:latest
    labels:
      - "autoheal=true"
    environment:
      - OLLAMA_NUM_THREADS=8
      - OLLAMA_CONTEXT_SIZE=4096
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      timeout: 5s
      retries: 3
      start_period: 30s

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: ./
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/app/packages/server
      - ./packages/types:/app/packages/types
    depends_on:
      llama:
        condition: service_healthy
        restart: true
    healthcheck:
      test: "curl -f http://api:3000/"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    env_file:
      - ./packages/server/.env
    restart: always

  interface:
    build:
      context: ./
      dockerfile: ./packages/interface/Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./packages/interface:/app/packages/interface
      - ./packages/types:/app/packages/types
    depends_on:
      api:
        condition: service_healthy
        restart: true
    healthcheck:
      test: "curl -f http://interface:5555/"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - VITE_API_URL=http://api:3000
    restart: always
