services:
  llama:
    image: ollama/ollama:latest
    labels:
      - "autoheal=true"
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      timeout: 5s
      retries: 3
      start_period: 30s

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      llama:
        condition: service_healthy
        restart: true
    healthcheck:
      test: "curl -f http://localhost:3000/"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - LLAMA_API_URL=http://llama:11434
      - API_URL=http://localhost:3000
      - ACCESS_TOKEN_EXPIRATION=1d
      - REFRESH_TOKEN_EXPIRATION=54000
      - JWT_SECRET=success
    restart: always
