services:
  llama:
    image: ollama/ollama:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:11434"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      llama:
        condition: service_healthy
        restart: true
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - API_URL=http://localhost:3000
      - ACCESS_TOKEN_EXPIRATION=1d
      - REFRESH_TOKEN_EXPIRATION=54000
      - JWT_SECRET=success
      - LLAMA_API_URL=http://llama:11434
    restart: always
