services:
  llama:
    image: ollama/ollama:latest
    labels:
      - "autoheal=true"
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      timeout: 5s
      retries: 3
      start_period: 30s

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=30
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server/sqlite.db:/app/sqlite.db
    depends_on:
      llama:
        condition: service_healthy
        restart: true
    healthcheck:
      test: "curl -f http://localhost:3000/"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    env_file:
      - ./packages/server/.env
    restart: always
